# docker-compose.yml
services:
  app:
    # Ganti ke bookworm-slim untuk mendukung native modules (glibc)
    image: node:22-bookworm-slim
    container_name: tpw_app
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - .:/app
    working_dir: /app
    # Pastikan binding ke 0.0.0.0 agar bisa diakses dari luar
    command: sh -c "npm install && npx next dev -H 0.0.0.0"
    environment:
      - VLLM_URL=http://llm:11434
      - STT_URL=http://stt:9000
    depends_on:
      - llm
      - stt

  stt:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: tpw_stt
    restart: unless-stopped
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper

  llm:
    image: ollama/ollama:latest
    container_name: tpw_llm
    restart: unless-stopped
    volumes:
      - ./ollama_data:/root/.ollama